# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" , "dev" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    env:
      DISPLAY: :0

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install mesa and patchelf
      run: |
        sudo apt-get install -y \
            libgl1-mesa-dev \
            libgl1-mesa-glx \
            libglew-dev \
            libosmesa6-dev \
            software-properties-common
        sudo apt-get install -y patchelf
        sudo apt-get update -y -qq
        sudo apt-get install -y xvfb x11-xserver-utils
        sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &               

    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[mujoco,encoder]"
        pip install 'r3m@git+https://github.com/facebookresearch/r3m.git'
        pip install 'vc_models@git+https://github.com/facebookresearch/eai-vc.git@9958b278666bcbde193d665cc0df9ccddcdb8a5a#egg=vc_models&subdirectory=vc_models'
    - name: Test with pytest
      run: |
        python robohive/tests/test_all.py
