# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install mesa and patchelf
      run: |
        sudo apt-get install -y \
            libgl1-mesa-dev \
            libgl1-mesa-glx \
            libglew-dev \
            libosmesa6-dev \
            software-properties-common
        sudo apt-get install -y patchelf
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git submodule update --recursive
        pip install -e .
        pip install free-mujoco-py
    - name: Test with pytest
      run: |
        python -c "import robohive, gym; gym.make('FrankaReachRandom-v0')"
